robot: "anymal_b"
robot_scene: "scene.xml"


print_scene_information: 1
enable_elastic_band: 0

motor_commands_topic: "rt/lowcmd"
low_state_topic: "rt/lowstate"
bridge_rate: 1000

enable_cameras: 0
enable_depth_cameras: 0
