robot: "anymal_d"
robot_scene: "scene.xml"


print_scene_information: 1
enable_elastic_band: 0

motor_commands_topic: "rt/lowcmd"
low_state_topic: "rt/lowstate"
bridge_rate: 1000

enable_cameras: 1
cameras:
  - name: "wide_angle_front"
    topic: "rt/camera/front"
    width: 640
    height: 480
    fps: 15
  - name: "wide_angle_rear"
    topic: "rt/camera/rear"
    width: 640
    height: 480
    fps: 10
    enabled: 0

enable_depth_cameras: 1
depth_cameras:
  - name: "depth_front_upper"
    topic: "rt/pointcloud/front_upper"
    width: 640
    height: 480
    fps: 5
    stride: 4
    min_distance: 0.5
    max_distance: 3.0
  - name: "depth_front_lower"
    topic: "rt/pointcloud/front_lower"
    width: 640
    height: 480
    fps: 5
    stride: 4
    min_distance: 0.5
    max_distance: 3.0
  - name: "depth_rear_upper"
    topic: "rt/pointcloud/rear_upper"
    width: 640
    height: 480
    fps: 5
    stride: 4
    min_distance: 0.5
    max_distance: 3.0
    enabled: 1
  - name: "depth_rear_lower"
    topic: "rt/pointcloud/rear_lower"
    width: 640
    height: 480
    fps: 5
    stride: 4
    min_distance: 0.5
    max_distance: 3.0
    enabled: 1
  - name: "depth_left"
    topic: "rt/pointcloud/left"
    width: 640
    height: 480
    fps: 5
    stride: 4
    min_distance: 0.5
    max_distance: 3.0
    enabled: 1
  - name: "depth_right"
    topic: "rt/pointcloud/right"
    width: 640
    height: 480
    fps: 5
    stride: 4
    min_distance: 0.5
    max_distance: 3.0
    enabled: 1
